name: 'Send releases to slack'
description: 'A Github action for posting release notes to slack'
inputs:
  webhook_url:  # id of input
    description: 'webhook url'
    required: true
  repo_name: # repo name
    description: 'repo_name'
    required: false
  body:
    description: 'JSON changelog output supported by https://www.npmjs.com/package/auto-changelog'
    required: true
  reverted_release:
    description: 'Is the release reverted? Boolean value'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'at-sign'
  color: 'gray-dark'
